// Angular.Dev/src/app/shared/accordian/accordian.component.ts
import { Component, Input } from '@angular/core';
import { AccordionItem } from '../../models/accordian-item.model';
import { NgClass, NgFor, NgForOf, NgIf } from '@angular/common';

@Component({
  selector: 'app-accordion',
  templateUrl: './accordian.component.html',
  imports: [NgFor, NgIf, NgClass]
})
export default class AccordionComponent {
  @Input() items: AccordionItem[] = [];
  openIndex: number | null = null;

  toggle(index: number): void {
    this.openIndex = this.openIndex === index ? null : index;
  }

  isOpen(index: number): boolean {
    return this.openIndex === index;
  }
  isArray(val: any): val is string[] {
    return Array.isArray(val);
  }
}

<div class="accordion">
  <div *ngFor="let item of items; let i = index" class="accordion-item">
    <button class="accordion-question" (click)="toggle(i)" [class.active]="isOpen(i)">
      {{ item.question }}
      <span class="arrow">
        <i [ngClass]="isOpen(i) ? 'arrow-up' : 'arrow-down'"></i>
      </span>
    </button>
    <div class="accordion-answer" [style.height]="isOpen(i) ? 'auto' : '0px'" [style.overflow]="'hidden'">
      <ng-container *ngIf="isArray(item.answer); else singleAnswer">
        <ul>
          <li *ngFor="let ans of item.answer">{{ ans }}</li>
        </ul>
      </ng-container>
      <ng-template #singleAnswer>
        <p>{{ item.answer }}</p>
      </ng-template>
    </div>
  </div>
</div>

// CSS.Dev/src/shared/accordian.tsx
import { useRef } from "react";
import { RiArrowDropDownLine } from "react-icons/ri";
import "../assets/accordian.css";

interface AccordionItemProps {
  question: string;
  answer: string | string[];
  isOpen: boolean;
  onClick: () => void;
}

export const AccordionItem: React.FC<AccordionItemProps> = ({
  question,
  answer,
  isOpen,
  onClick,
}) => {
  const contentRef = useRef<HTMLDivElement>(null);

  return (
    <div className="wrapper">
      <button
        className={`question-container ${isOpen ? 'active' : ''}`}
        onClick={onClick}
      >
        <p className="question-content">{question}</p>
        <RiArrowDropDownLine className={`arrow ${isOpen ? 'active' : ''}`} />
      </button>

      <div
        ref={contentRef}
        className="answer-container"
        style={{
          height: isOpen ? `${contentRef.current?.scrollHeight}px` : '0px',
          overflow: 'hidden',
          transition: 'height 0.3s ease',
        }}
      >
        <div className="answer-content">
          {Array.isArray(answer) ? (
            <ul>
              {answer.map((item, idx) => (
                <li key={idx}>{item}</li>
              ))}
            </ul>
          ) : (
            <p>{answer}</p>
          )}
        </div>
      </div>
    </div>
  );
};
