// Angular.Dev/src/app/layout/left-panel.component.ts
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";

@Component({
    selector: 'left-panel',
    templateUrl: './left-panel.component.html',
    standalone: true,
    imports: [RouterLink]
})
export class LeftPanel {
    nav = []
}
<aside id="leftPanel" class="left-panel">
    <ul>
        <li><a routerLink="/qa">Questions and Answers</a></li>
        <li><a routerLink="/todo">To Do</a></li>
    </ul>
</aside>

// React.Dev/src/layout/leftPanel.tsx
import { Link } from 'react-router-dom';

export default function LeftPanel() {
    return(
        <>
            <aside id="leftPanel" className="left-panel">
                <nav>
                    <ul>
                        <li><Link to="/React/qa">Questions & Answers</Link></li>
                        <li><Link to="/React/projects">Projects</Link></li>
                    </ul>
                </nav>
            </aside>
        </>
    )
}
