// React.Dev/src/features/qa.tsx
import { useEffect, useState } from "react";
import data from "./qa.data";
import { AccordionItem } from "../shared/accordian";
import { useSearch } from "../core/context/searchContext";


const QuestinosAnswers = () => {
  const [activeIndex, setActiveIndex] = useState(null);
  const { searchTerm } = useSearch();

  const filtered = data.filter((item) => 
    item.question.toLowerCase().includes(searchTerm.toLowerCase())
  );
  const handleItemClick = (index: any) => {
    setActiveIndex((prevIndex) => (prevIndex === index ? null : index));
  };
  useEffect(() => {
    console.log("QA json length ", data.length);
  }, []);
  return (
    <div className="container">
      {filtered.map((item, index) => (
        <AccordionItem
          key={index}
          question={item.question}
          answer={item.answer}
          isOpen={activeIndex === index}
          onClick={() => handleItemClick(index)}
        />
      ))}
    </div>
  );
};

export default QuestinosAnswers;

// Angular.Dev/src/app/components/qa/qa.component.ts
import { ChangeDetectorRef, Component } from '@angular/core';
import AccordionComponent from '../../shared/accordian/accordian.component';
import { Data } from './qa.data';
import { AccordionItem } from '../../models/accordian-item.model';
import { SearchService } from '../../shared/services/search.service';

@Component({
  selector: 'questions-answer',
  imports: [AccordionComponent],
  templateUrl: './qa.component.html'
})
export class QuestionsAnswers {
  data:AccordionItem[] = Data;
  activeIndex: number | null = null;
  filteredData = [...this.data];
  constructor(private cdr: ChangeDetectorRef, private searchService: SearchService) {}
  handleItemClick(index: number) {
    // Toggle same item, otherwise open selected
    this.activeIndex = this.activeIndex === index ? null : index;
  }
  ngOnInit(): void {
    console.log("ngOnInit QA data ", this.data.length);
    this.searchService.searchTerm$.subscribe(term => {
      const lower = term.toLowerCase();
      this.filteredData = this.data.filter(item =>
        item.question.toLowerCase().includes(lower)
      );
      this.cdr.detectChanges(); // ✅ manually trigger view update
    });
  }
}
